##################
### jsp set
##################
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&amp;useUnicode=true&amp;charaterEncoding=utf-8
    username: root
    password: root
  
##################
### log set
##################
logging:
  file: /var/log/spring-boot.log
  level.*: INFO
  level.site.blmdz: DEBUG
  
##################
### server set
##################
server:
  context-path: /
  port: 8082
  session:
    timeout: 1800
    
##################
### mybatis set
##################
mybatis:
  mapperLocations: classpath*:mapper/*Mapper.xml
  typeAliasesPackage: site.blmdz.model
  
##################
### other set
##################
jsp:
  debugger: true
  shiro:
    login: /login
    success: /success
    unauth: /unauth
    ehcache:
      enable: true
      timeout: 120
