###################################################
### jsp set
###################################################
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
###################################################
### log set
###################################################
logging:
  file: /var/log/spring-boot.log
  level.*: INFO
  level.site.blmdz: DEBUG
###################################################
### server set
###################################################
server:
  context-path: /
  port: 8082
  error: redirect:/errors
  session:
    timeout: 10
###################################################
### other set
###################################################

